language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
  matrix:
  - CI=true
  global:
    secure: JWnwEHUYo+CGpWERA6ut2qUiGOpcbK1T6dWd+EH98dchN9y6FK5Dxyvz8LujVJmmyCKEwZHRb1+DKAYikZAi+GNb2ba+y/UGyxuQO0Vu+FUjeHfpzAWdiK3qhPco/+ckjos7j3Nr5b+aP1dLOXEj9RvcwZcSDvRTJrqJbixKWs7UGITBbzfxfjyOfcSUV2vwI0HjkTVkWROD8HLCROFELh+y5V/z3EuXb0mNsBQQL/oZ9qZsGmW3ivrPfl3eEfC5A3DW1ILKzuCFxROflUp4R9Fjzs4hVxMDrctOcrZGRF9VcYQZ8wKUK45tLOPAsQlMJaskKWGZj2IZKgpgOzd683iKw4UJuQLXlhs/u+ReQsvrMAA8ggIgtnz6xNjldQYmpQizH1qZ8TXPn+augJ09N9IIp1ZDbtelWVbGJU3nK/cHMfVkHpNtRAaqs+4SjsoSFana4U4nXULW2G2EFTxk+Pio3ONNM9sv4Baa8rhFezWP+e3OqABTv8I7VNCXL+OrLkiU66+d+ezrEJvKslOEzkHs8I+0TIZGNI/PGuw/8o0Dix31kFFSdDRT4U2y+wXttKM41O4CQU8Dt2HxDb7fFsJCrEYW7vJ/pZcy1Pwm7ilSedSaAcVF1HdXOIJB9IzCSouWU9DGaMN4WAjfFT3xF0v2h2CNmfM4DmAgtG83Qeo=
deploy:
  provider: heroku
  api_key:
    secure: j3Mg0amD/2a+tIqGXZiMMUxgGIeuZ5RsscFW3HD/d4714SgglI+mtg6KTN7zGjpqBttKrpZm/9S/U35urSaosl/9ubRgntyAtjsl/GaBfdHZkuM+v5C4ebJOICN114rXrawSWLmuNfRsy2P51raqDlK7ot7XrTrMZOPA4cLt9wIlBDfLVyZBB0Uz1O92NMl+KN1GhC2bQc3cjBHH7BdOA6ivVSkdFVqRftb3fF5IhhJncU0qE+aEDuu9B5mXQ4Vs1KZuVNCXGUEVZ+8D2PtoDkakXTlkxUhiNCiDYh42zbs1imhlOig15i9ybFhbFbtgrhMTtouPSRmRt1Ks0Ftf1mZKhIiKch8PBKucR3lFZFF0JEayChZ2mq2gTj5TCuYqC8DHf00OhdKhB0I2Yl105ujR954dG++SXYOeyiwCuuaF/AdWRM8g4GHaN0AUoYR8XLeiFts7rF31o4k0QGlwANsLdbTqk5BqG7P9TdvBVjLmykih3+fzsG4Ecn4Io6LBwvGC3S37haWG32sCxnsPQ4/qEJApGywFHit0UxJOQTU9FWUxYGk6D8mG4vEIi/OZsJeYzh0/fYP8zb3Lay5TeWnO2GoFU3GLpgTbq/veI58/LxhLKVFsat9+MCy5W8+I6B/9CJjJ+gMb1JM0eeWu3z2nQYK1MxGiHFnzXdqkD4o=
  app: https://jabber-jaw.herokuapp.com/
  on:
    repo: MikeyB2/jabber-jaw-client
