language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
  matrix:
  - CI=true
  global:
    secure: WYdXErZ+a9pnS4DtaO6hA7E34SiqB1NobVAxKQB8+ljdTyEnu2bsjZ/R1wH0nQIasqV9ZTZZwNKfzROrpLzLklP24rOTQKowubaKmDE1enRLbSNJWQlUIyVu6djzgmIUJfvz4PRUSDPX/OVj0k1JoL2f4RqQQgW0x0Kt1ED3x12RGg2DOBvV9D6YyKaJeG9qgNz3vCM/HvVhoz3wMbE01o33NMuZW8mqHjyjg83jqdIIjlFWtQ9YbsUpCQ6/ALQXP7zj2t9aGwjoOIHdN2x7IklLnAg8Exdvz1PMvhmuXVc4Q0LWfOU6SeZL7Ge4cIvTmdnFWngMlnb1bV+G4uf81qkhR5igbGRLNckr+cSZHjQZcwm9PxnPGiw7VQY+o4Mjc+ePHJSjc3Ac30TbR1iPuTdij48MTB67IOrXKEcc/Gf855NPLwgOf+1iyC6RnNvFZWcX5KUUf+KW78egVQah7InA73f7iK3Z/Q9vLTRgfWMGtbYuvE6u1Lh6PP5kaxxlshOiV9fz+EiMsgH1jIrnT9008mBq/MBDaTCyCQR9kriCCPcREPNHYOKqZKFxfwM9HdAruXt3Bb3DgCjh1RCHCLvIjqyt2eUpcd1tiy8odusCqyrERiG0h21TrjrO0Boibv8WdEcF+rNkB8HKO1FcsotJrmQ28bzgDl7IWkPqGaU=
deploy:
  provider: heroku
  api_key:
    secure: RTFkA9HgsNAShqA+G/z2jwJ33q4I/TFjlX/hGkCQbUXz3osrEItfAtceQSHuwfLGYWVwnjK5nHVufFUFQ7ClpsUBsqzYoJ4nJ9HOz+dXnZDoZwDHs4hDxsGorAo3tPMiNCleGX2AN2ts9CC6cRkHLWrSN4CxkNe8iQmIukEw520Meue6jI38MQCScON8sQdUOkk1b/F4ePZyNlAuFTNR5JLQMw2v8FVDsPfXdYKFXGAXC0x9hM93ei80SeVE1xUhx2BGoXkAuD/6cjGs7Aks4jB9jx1mZ+L8zxb3lvGzywoKC9JBosI29n2Gobm2oKD1U96p6s9tDk2UFNOPZjYEXQHs0rOrLFYPMv6HOcPdxv45KDoLvvBKbmazZkZ36YBEWPYlpTF1+Y4oAc8EYuYYLXc2llyytFhpuVJAwutCs0KYXGte4LK5pC/1x84Q6j7rTjLb/s29icWWkzJbcnVU39eRVYBP1KDuoeajYbTaUwA5bacBby9Ni89qEN2L/FyLaaZ8B3OLINQ247S1aTpH7C27q4PGFEnc3Z+xMoNaXtMOcPGXLaNHf0/lCQjHgytwZAlb9O9Ug1lgaLEmqqdOQpRb3i8r6o0ZhCMuSMqYJIGm2ICQHasMJfHjJDlncshy+Ptm9E8YndK/9y1pTKpXCSElR+qCzQLD6+qefY78M9g=
  app: https://hidden-spire-38773.herokuapp.com/
  on:
    repo: MikeyB2/jabber-jaw-client
